package lk.ijse.dep.Util;

public enum TextField {
    IDA, NAME, PASSWORD,IDC,ADDRESS,CONTACT,EMAIL,IDCS, DESCRIPTION, DATE, STATUS, IDD, AMOUNT, METHOD, IDP, PRODUCT, IDS, POSITION, IDE, DOUBLE, QTY, IDI
}
